apiVersion: v1
kind: Pod
metadata: 
  name: gamingapplicationpod
spec:
  containers:
    - name: gaming-application-conatiner
      image: atulgoel8717/gaming-zone
      ports: 
        - containerPort: 80